spring.application.name=demopg
spring.application.name=SpringBootSecurityPostgresqlApplication

#spring.datasource.url=jdbc:postgresql://localhost:5432/personajes_videojuegos
#spring.datasource.username=postgres
#spring.datasource.password=brandonjuarez

spring.datasource.url=jdbc:postgresql://pg-123faca8-principiosdiseno-b09f.g.aivencloud.com:13732/personajesdb2
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ddXtKWuAQLClvTCzrrr


spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# App Properties
app.jwtSecret=aVeryLongSecureSecretKeyForHS512AlgorithmThatIsAtLeast256BitsLongAndWillWorkProperly2024!
app.jwtExpirationMs=86400000

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000
